### ISSUE TITLE
Update veda-pipeline-tasks to support multiple assets

### ISSUE THREAD

**Issue by slesaad** [NASA-IMPACT/veda-pipeline-tasks#13]
# Description

Based on the ADR [here](https://github.com/NASA-IMPACT/veda-architecture/pull/274/files), we need to update the veda-pipeline-tasks to support multiple assets for items.

A simple script is added to the ADR.

**Comment by moradology** [comment]
A couple of tasks that are worth bundling into this effort:
1. separation of cogification/upload from stac creation
2. removal of https://github.com/NASA-IMPACT/veda-pipeline-tasks and the submodule approach (this is proving too costly to develop against)

A couple of drafts to monitor here:
1. https://github.com/NASA-IMPACT/veda-data-airflow/pull/82
2. https://github.com/NASA-IMPACT/veda-pipeline-tasks/pull/14
