### ISSUE TITLE
Investigate or update proj extension version to 0.1.0

### ISSUE THREAD

**Issue by anayeaye** [NASA-IMPACT/veda-pipeline-tasks#9]
# What
Update the proj extension version produced for new STAC items with COG assets. This is likely an upgrade to the version of rio-stac used to create the stac item for an ingested geotiff. 

> **Note** if this is a time intensive upgrade, we should document the work needed and hold--we will be fixing the data type of the stored proj as a part of this [veda-backend ingest API work](https://github.com/NASA-IMPACT/veda-architecture/issues/215).

# Bug report
https://github.com/NASA-IMPACT/veda-data/issues/57

# AC
- [x] new stac metadata generated for COG assets use proj v0.1.0
- [ ] open an issue in veda-data-pipelines capturing how the change was implemented here so that the update can be back-ported if needed
**OR**
- [ ] if it is determined that this upgrade costs more to implement than benefits users, document why the new version of the extension is not used.

# Not AC
Backwards correction of existing records. That task will be tracked in veda-backend.

**Comment by moradology** [comment]
This issue was actually handled in the airflow implementation that's currently deployed: https://github.com/NASA-IMPACT/veda-data-airflow/blob/dev/docker_tasks/build_stac/requirements.txt#L7

I think we can safely close this issue!
